# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ess.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 853)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.display_text = QtWidgets.QLabel(self.centralwidget)
        self.display_text.setGeometry(QtCore.QRect(340, 10, 401, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.display_text.setFont(font)
        self.display_text.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.display_text.setObjectName("display_text")
        self.black_bg = QtWidgets.QLabel(self.centralwidget)
        self.black_bg.setGeometry(QtCore.QRect(0, 0, 1091, 801))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        self.black_bg.setFont(font)
        self.black_bg.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.black_bg.setText("")
        self.black_bg.setPixmap(QtGui.QPixmap("black_bg.jpg"))
        self.black_bg.setScaledContents(True)
        self.black_bg.setObjectName("black_bg")
        self.dashboard = QtWidgets.QLabel(self.centralwidget)
        self.dashboard.setGeometry(QtCore.QRect(110, 60, 871, 531))
        self.dashboard.setText("")
        self.dashboard.setPixmap(QtGui.QPixmap("dashboard.jpg"))
        self.dashboard.setScaledContents(True)
        self.dashboard.setObjectName("dashboard")
        self.mobile_distraction_icon = QtWidgets.QLabel(self.centralwidget)
        self.mobile_distraction_icon.setGeometry(QtCore.QRect(830, 610, 141, 121))
        font = QtGui.QFont()
        font.setFamily("Proxy 1")
        self.mobile_distraction_icon.setFont(font)
        self.mobile_distraction_icon.setText("")
        self.mobile_distraction_icon.setPixmap(QtGui.QPixmap("mobile_distraction.png"))
        self.mobile_distraction_icon.setScaledContents(True)
        self.mobile_distraction_icon.setObjectName("mobile_distraction_icon")
        self.seatbelt_icon = QtWidgets.QLabel(self.centralwidget)
        self.seatbelt_icon.setGeometry(QtCore.QRect(110, 610, 171, 121))
        font = QtGui.QFont()
        font.setFamily("Proxy 1")
        self.seatbelt_icon.setFont(font)
        self.seatbelt_icon.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.seatbelt_icon.setText("")
        self.seatbelt_icon.setPixmap(QtGui.QPixmap("seatbelt.png"))
        self.seatbelt_icon.setScaledContents(True)
        self.seatbelt_icon.setObjectName("seatbelt_icon")
        self.drowsy_icon = QtWidgets.QLabel(self.centralwidget)
        self.drowsy_icon.setGeometry(QtCore.QRect(350, 610, 141, 121))
        font = QtGui.QFont()
        font.setFamily("Proxy 1")
        self.drowsy_icon.setFont(font)
        self.drowsy_icon.setText("")
        self.drowsy_icon.setPixmap(QtGui.QPixmap("drowsy.png"))
        self.drowsy_icon.setScaledContents(True)
        self.drowsy_icon.setObjectName("drowsy_icon")
        self.yawn_icon = QtWidgets.QLabel(self.centralwidget)
        self.yawn_icon.setGeometry(QtCore.QRect(610, 620, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Proxy 1")
        self.yawn_icon.setFont(font)
        self.yawn_icon.setText("")
        self.yawn_icon.setPixmap(QtGui.QPixmap("yawning.png"))
        self.yawn_icon.setScaledContents(True)
        self.yawn_icon.setObjectName("yawn_icon")
        self.black_bg.raise_()
        self.dashboard.raise_()
        self.display_text.raise_()
        self.mobile_distraction_icon.raise_()
        self.seatbelt_icon.raise_()
        self.drowsy_icon.raise_()
        self.yawn_icon.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.display_text.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#e32f17;\">WARNING!</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
